version: 0.0
os: linux
files:
  - source: /target/myweb-0.12.0.war
    destination: /opt/tomcat10/webapps
hooks:
  BeforeInstall:
    - location: stop_tomcat.sh
  AfterInstall:
    - location: start_tomcat.sh
      timeout: 30
