version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
artifacts:
  files:
    - target/*.war
  discard-paths: yes
