version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Performing Test
      - zip -r web1.zip target/*.war appspec.yml start_tomcat.sh stop_tomcat.sh
artifacts:
  type: zip
  files:
    - web1.zip
  discard-paths: yes
