version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - mvn install
  post build:
    commands:
	  - echo "zipping files"
	  - mv target/*.war .
	  - zip -r mywebapp.zip appspec.yml start_tomcat.sh stop_tomcat.sh *.war
artifacts:
  type: zip
  files:
    - mywebapp.zip
  discard-paths: yes
